Repository wisdom08/dev-hash, pull requests merged in 2022-08, with the labels that each got.

#5 공통 응답 바디 개발
  src/main/java/com/one/devhash/exception/FailedConvertingException.java
  src/main/java/com/one/devhash/global/error/ErrorResponse.java
  src/main/java/com/one/devhash/global/error/GlobalExceptionHandler.java
  src/main/java/com/one/devhash/global/error/exception/BusinessException.java
  src/main/java/com/one/devhash/global/error/exception/EntityNotFoundException.java
  src/main/java/com/one/devhash/global/error/exception/ErrorCode.java
  src/main/java/com/one/devhash/global/error/exception/InvalidValueException.java
  src/main/java/com/one/devhash/global/response/ApiUtils.java
  src/main/java/com/one/devhash/global/response/CommonResponse.java
Labels: enhancement

#6 상품 등록 및 조회
  src/main/java/com/one/devhash/controller/ProductController.java
  src/main/java/com/one/devhash/domain/Product.java
  src/main/java/com/one/devhash/domain/Timestamped.java
  src/main/java/com/one/devhash/global/error/exception/ErrorCode.java
  src/main/java/com/one/devhash/repository/ProductRepository.java
  src/main/java/com/one/devhash/service/ProductService.java
Labels: enhancement

#9 채팅 기능 구현
  build.gradle
  src/main/java/com/one/devhash/config/WebSocketConfig.java
  src/main/java/com/one/devhash/controller/ChatController.java
  src/main/java/com/one/devhash/controller/RoomController.java
  src/main/java/com/one/devhash/domain/Chat.java
  src/main/java/com/one/devhash/domain/Room.java
  src/main/java/com/one/devhash/dto/chatting/ChatMessage.java
  src/main/java/com/one/devhash/dto/chatting/ChatResponseDto.java
  src/main/java/com/one/devhash/repository/ChatRepository.java
  src/main/java/com/one/devhash/repository/RoomRepository.java
  src/main/java/com/one/devhash/service/ChatService.java
Labels: enhancement

#10 인증 기능 구현
  build.gradle
  src/main/java/com/one/devhash/DevHashApplication.java
  src/main/java/com/one/devhash/controller/AuthController.java
  src/main/java/com/one/devhash/domain/Product.java
  src/main/java/com/one/devhash/domain/RefreshToken.java
  src/main/java/com/one/devhash/domain/User.java
  src/main/java/com/one/devhash/dto/user/TokenResponseDto.java
  src/main/java/com/one/devhash/dto/user/UserRequestDto.java
  src/main/java/com/one/devhash/global/error/exception/ErrorCode.java
  src/main/java/com/one/devhash/repository/RefreshTokenRepository.java
  src/main/java/com/one/devhash/repository/UserRepository.java
  src/main/java/com/one/devhash/security/MyUserDetailsService.java
  src/main/java/com/one/devhash/security/config/CorsConfig.java
  src/main/java/com/one/devhash/security/config/WebSecurityConfig.java
  src/main/java/com/one/devhash/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/one/devhash/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/one/devhash/security/jwt/JwtTokenFilter.java
  src/main/java/com/one/devhash/security/jwt/JwtTokenFilterConfigurer.java
  src/main/java/com/one/devhash/security/jwt/JwtTokenProvider.java
  src/main/java/com/one/devhash/service/ProductService.java
  src/main/java/com/one/devhash/service/UserService.java
  src/main/java/com/one/devhash/utils/AuditingFields.java
Labels: enhancement

#13 추가 커밋 넣은 부분 재수정
  src/main/java/com/one/devhash/security/config/WebSecurityConfig.java
Labels: bug

#16 채팅 추가 개발
  src/main/java/com/one/devhash/controller/ChatController.java
  src/main/java/com/one/devhash/controller/RoomController.java
  src/main/java/com/one/devhash/domain/Chat.java
  src/main/java/com/one/devhash/domain/Room.java
  src/main/java/com/one/devhash/domain/User.java
  src/main/java/com/one/devhash/dto/chatting/ChatResponseDto.java
  src/main/java/com/one/devhash/dto/chatting/RoomResponseDto.java
  src/main/java/com/one/devhash/global/error/exception/ErrorCode.java
  src/main/java/com/one/devhash/repository/RoomRepository.java
  src/main/java/com/one/devhash/service/ChatService.java
  src/main/java/com/one/devhash/service/RoomService.java
  src/main/java/com/one/devhash/service/UserService.java
Labels: enhancement

#12 Feature/#11 image
  build.gradle
  src/main/java/com/one/devhash/config/AwsS3Config.java
  src/main/java/com/one/devhash/controller/ProductController.java
  src/main/java/com/one/devhash/domain/ImageTarget.java
  src/main/java/com/one/devhash/domain/Imagefile.java
  src/main/java/com/one/devhash/domain/Product.java
  src/main/java/com/one/devhash/domain/ProductStatus.java
  src/main/java/com/one/devhash/dto/product/ProductRequestDto.java
  src/main/java/com/one/devhash/dto/product/ProductResponseDto.java
  src/main/java/com/one/devhash/global/error/exception/ErrorCode.java
  src/main/java/com/one/devhash/repository/ImagefileRepository.java
  src/main/java/com/one/devhash/repository/ProductRepository.java
  src/main/java/com/one/devhash/service/ProductService.java
  src/main/java/com/one/devhash/service/S3Service.java
Labels: enhancement

#17 코드 병합 후 발생하는 문제 해결
  src/main/java/com/one/devhash/domain/Chat.java
  src/main/java/com/one/devhash/domain/Room.java
  src/main/java/com/one/devhash/domain/User.java
  src/main/java/com/one/devhash/repository/ImagefileRepository.java
  src/main/java/com/one/devhash/service/ProductService.java
  src/main/java/com/one/devhash/service/RoomService.java
Labels: bug

#18 유저 프로필사진 기능 추가
  src/main/java/com/one/devhash/controller/AuthController.java
  src/main/java/com/one/devhash/service/S3Service.java
  src/main/java/com/one/devhash/service/UserService.java
Labels: enhancement

#23 헤로쿠 설정 추가
  Profile
  build.gradle
  system.properties
Labels: documentation

#22 Feature/#19 mypage
  src/main/java/com/one/devhash/controller/MypageController.java
  src/main/java/com/one/devhash/dto/user/UserResponseDto.java
  src/main/java/com/one/devhash/repository/ProductRepository.java
  src/main/java/com/one/devhash/service/MypageService.java
  src/main/java/com/one/devhash/service/ProductService.java
Labels: enhancement

#25 헤로쿠 설정 중 오타난 파일명 변경
  Procfile
  Profile
Labels: bug

#26 Feature/#24 wish
  src/main/java/com/one/devhash/controller/MypageController.java
  src/main/java/com/one/devhash/controller/WishController.java
  src/main/java/com/one/devhash/domain/Wish.java
  src/main/java/com/one/devhash/dto/product/MypageResponseDto.java
  src/main/java/com/one/devhash/dto/product/ProductResponseDto.java
  src/main/java/com/one/devhash/global/error/exception/ErrorCode.java
  src/main/java/com/one/devhash/repository/WishRepository.java
  src/main/java/com/one/devhash/service/MypageService.java
  src/main/java/com/one/devhash/service/ProductService.java
  src/main/java/com/one/devhash/service/WishService.java
Labels: enhancement

#27 DDL AUTO 옵션 변경
  src/main/resources/application-prod.yaml
Labels: invalid

#30 cors 관련 수정
  src/main/java/com/one/devhash/security/config/CorsConfig.java
Labels: enhancement

#31 FetchType 변경
  src/main/java/com/one/devhash/domain/Product.java
Labels: bug

#32 feat: #29 스웨거 추가
  build.gradle
  src/main/java/com/one/devhash/config/SwaggerConfig.java
Labels: enhancement

#33 feat: #29 스웨거 설명 추가
  src/main/java/com/one/devhash/controller/AuthController.java
  src/main/java/com/one/devhash/controller/ChatController.java
  src/main/java/com/one/devhash/controller/MypageController.java
  src/main/java/com/one/devhash/controller/ProductController.java
  src/main/java/com/one/devhash/controller/RoomController.java
  src/main/java/com/one/devhash/controller/WishController.java
Labels: enhancement

#35 fix: 상품 삭제시 작성자 확인 오류
  src/main/java/com/one/devhash/controller/WishController.java
  src/main/java/com/one/devhash/service/ProductService.java
Labels: bug

#36 fix: 상품 삭제 오류 수정
  src/main/java/com/one/devhash/service/ProductService.java
Labels: bug

#37 fix: 찜한 상품 조회 오류 수정
  src/main/java/com/one/devhash/controller/ProductController.java
  src/main/java/com/one/devhash/service/MypageService.java
Labels: bug

#39 채팅방 응답 바디 데이터 수정
  src/main/java/com/one/devhash/controller/RoomController.java
  src/main/java/com/one/devhash/dto/chatting/RoomResponseDto.java
  src/main/java/com/one/devhash/service/RoomService.java
Labels: enhancement

#38 파일 없이 상품 등록 안되는 오류
  src/main/java/com/one/devhash/controller/ProductController.java
Labels: bug

#40 채팅방 목록 조회 시, 전체 내 채팅 목록이 아닌 내가 채팅을 요청 보냈을 때만 나오는 이슈 수정
  src/main/java/com/one/devhash/repository/RoomRepository.java
  src/main/java/com/one/devhash/service/ProductService.java
  src/main/java/com/one/devhash/service/RoomService.java
Labels: bug
